spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip_manager?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: lee66627586@gmail.com
    password: "kpxv blha bmlw dxmj"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: "${JWT_SECRET_KEY:6d9f6e1c2d7245d4afee5e2f6d4e1a38f0c4e92b438d846c8d93564f3f6a0b21}"
  access-token-validity: 3600000 # Access Token 유효 시간 (1시간)
  refresh-token-validity: 1209600000 # Refresh Token 유효 시간 (2주)
