spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trip_manager?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop
